# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.6.9"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests

deploy:
  provider: heroku
  api_key: "304fb9d5-08a6-40e8-8551-a6ecb1282048"
  app: muii-g2-api-location
